config/routes.rb
Rails.application.routes.draw do

  # ログイン関係
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  # ユーザー関係
  root 'homes#top'
  get '/about' => 'homes#about'
  resources :post_images do
    resource :favorites, only:[:create, :destroy]
    resources :comments, only:[:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    member do
      get :following, :followers
    end
  end
  resources :articles, only: [:index, :show]

  resources :relationships, only: [:create,:destroy]
  # 管理者関係
  namespace :admin do
    root 'homes#top'
    resources :articles
    resources :users, only: [:index, :show, :edit, :update, :destroy]
  end

end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :admin
  attachment :article_image

  def self.search(search) #self.はArticle.を意味する
    if search
      where(['article_title LIKE ?', "%#{search}%"]) #検索とuseanameの部分一致を表示。
    else
      all #全て表示させる
    end
  end

  validates :article_title, presence: :true
  validates :article_image, presence: :true
  validates :article_content, presence: :true
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
  before_action :authenticate_admin! # 「ログイン認証されていなければ、ログイン画面へリダイレクトする」機能を実装

  def new
    @article = Article.new
  end

  def index
    @articles = Article.all.order(created_at: :desc).search(params[:search])
  end

  def create
    @article = Article.new(article_params)
    @article.admin_id = current_admin.id
    if @article.save
    redirect_to admin_articles_path, notice: "記事が作成されました"
    else
      render 'new'
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
    redirect_to admin_article_path(@article), notice: "記事が更新されました"
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    if @article.destroy
    redirect_to admin_articles_path, notice: "記事が削除されました"
    else
      render 'edit'
    end
  end

  private
  def article_params
    params.require(:article).permit(:article_title, :article_content, :article_image)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all.order(created_at: :desc).search(params[:search])
  end

  def show
    @article = Article.find(params[:id])
  end
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <h1 class="page-title animate__animated animate__rotateInUpLeft">Articles</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-12 animate__animated animate__rotateInUpRight">
      <p class="page-title-translate">記事一覧</p>
      <%= form_tag(articles_path, :method => "get") do %>
        <%= text_field_tag :search, '', placeholder: "タイトル検索" %>
        <%= submit_tag "Search" ,:article_title => nil ,class: "btn btn-success btn-xs"%>
      <% end %>
    </div>
  </div>
  <div class="row animate__animated animate__rotateInUpLeft">
    <% @articles.each do |article| %>
      <div class="col-1 article-side-visual-left"></div>
      <div class="col-10 article-box">
        <div class="article-index-title">
          <%= link_to article_path(article) do %>
            <h2><span class="index-title"><%= article.article_title %></span></h2>
          <% end %>
        </div>
        <div class="article-image">
          <%= link_to article_path(article) do %>
            <%= attachment_image_tag article, :article_image, width:"100%", height:"100%" %>
          <% end %>
        </div>
        <div id="created-at-index"><p>投稿日｜<%= article.created_at.strftime('%Y/%m/%d') %></p></div>
      </div>
      <div class="col-1 article-side-visual-right"></div>
    <% end %>
  </div>
</div>

app/views/articles/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 animate__animated animate__fadeInTopLeft">
      <h1 class="page-title">Article about</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-12 animate__animated animate__fadeInTopRight">
      <p class="page-title-translate">記事詳細</p>
    </div>
  </div>
  <div class="row animate__animated animate__backInUp">
    <div class="col-1 show-side"></div>
    <div class="col-10 article-container">
      <div class="article-title">
        <h2><span class="show-title"><%= @article.article_title %></span></h2>
      </div>
      <div class="article-image">
        <%= attachment_image_tag @article, :article_image, width:"100%", height:"100%" %>
      </div>
      <div class="article-content">
        <%= @article.article_content.html_safe %>
      </div>
      <p id="article-created-at">投稿日｜<%= @article.created_at.strftime('%Y/%m/%d') %></p>
    </div>
    <div class="col-1"></div>
  </div>
</div>