config/routes.rb
Rails.application.routes.draw do

  # ログイン関係
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  # ユーザー関係
  root 'homes#top'
  get '/about' => 'homes#about'
  resources :post_images do
    resource :favorites, only:[:create, :destroy]
    resources :comments, only:[:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    member do
      get :following, :followers
    end
  end
  resources :articles, only: [:index, :show]

  resources :relationships, only: [:create,:destroy]
  # 管理者関係
  namespace :admin do
    root 'homes#top'
    resources :articles
    resources :users, only: [:index, :show, :edit, :update, :destroy]
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :post_images, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :profile_image

  validates :name, presence: true, length: { minimum: 2, maximum: 10 }
  # メールアドレスをDBに保存する前に小文字に変換
  before_save { self.email = email.downcase }
  # メールアドレスのフォーマットの検証
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  # メールアドレスの存在性の検証、一意性の検証
  validates :email, presence: true, length: { maximum: 50 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false}

  has_many :active_relationships, class_name: "Relationship",
            foreign_key: "follower_id",
            dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship",
            foreign_key: "followed_id",
            dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  #ユーザーをフォローする
  def follow(other_user)
    following << other_user
  end

  #ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  #現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end

  # ゲストユーザーを探す、ゲストユーザーを作成する
  def self.guest
    # find_or create_by = 引数の条件に該当するデータがあればそれを返す(find_by)なければ作成(create)
    find_or_create_by!(name: 'ゲストユーザー', email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64 # SecureRandom = 乱数生成、urlsafe_base64 = ランダムでURL-safeなbase64文字列を生成して返す
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.all.page(params[:page]).per(15)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User(params[:id])
    if @user.update(user_params)
    redirect_to admin_user_path(@user), notice: "会員情報を更新しました"
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
    redirect_to admin_users_path, notice: "会員情報を削除しました"
    else
      render 'show'
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  before_action :check_guest, only: :create

  def check_guest
    if params[:user][:email].downcase == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザーの情報の変更・削除はできません'
    end
  end

  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  before_action :check_guest, only: [:update, :destroy]

  def check_guest
    if resource.email == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザー情報の変更・削除はできません'
    end
  end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def new_guest
    user = User.guest
    sign_in user
    redirect_to post_images_path, notice: 'ゲストユーザーとしてログインしました'
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :user_restrict, only:[:edit, :destroy]
  before_action :check_guest, only: [:update]

  def index
    @users = User.all.page(params[:page]).per(15)
  end

  def show
    @user = User.find(params[:id])
    @post_images = @user.post_images
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "会員情報を更新しました"
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params)
    @user.destroy
    redirect_to root_path, notice: "退会しました"
  end

  def following
    @user = User.find(params[:id])
    @users = @user.following
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :profile_image)
  end

  def user_restrict
    user = User.find(params[:id])
    if user != current_user
      redirect_to post_images_path, notice: "⚠️他人の会員情報は編集できません"
    end
  end

  def check_guest
    @user = User.find(params[:id])
    if @user.email == 'guest@example.com' && @user.name == 'ゲストユーザー'
      redirect_to user_path(@user.id), notice: 'ゲストユーザーの情報は変更できません'
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <h1 class="page-title">Users</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <p class="page-title-translate">会員一覧</p><br>
    </div>
  </div>
  <div class="row">
    <div class="col-1"></div>
    <div class="col-10 users-contents" style="padding: 0px;">
    <table class="table table-hover">
      <thead class="thead-dark">
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% users.each do |user| %>
        <tr>
          <td class="align-middle">
            <%= attachment_image_tag user, :profile_image, size:'50x50', class: "rounded-circle float-left", size:"50x50" ,fallback:"noimage.png" %>
          </td>
          <td class="align-middle"><%= user.name %></td>
          <td class="align-middle"><%= link_to '詳細', user_path(user) %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate users, class: "text-center" %>
    </div>
    <div class="col-1"></div>
  </div>
</div>

app/views/users/_stats.html.erb
<% @user ||= current_user %>
  <h5>
    フォロー　：　<%= link_to following_user_path(@user) do %><%= @user.following.count %><% end %>
  </h5>
  <h5>
    フォロワー　：　<%= link_to followers_user_path(@user) do %><span id="followers"><%= @user.followers.count %></span><% end %>
  </h5>

app/views/users/edit.html.erb
<div class="container animate__animated animate__fadeIn">
  <div class="row">
    <div class="col-12">
      <h1 class="page-title">Edit My page</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <p class="page-title-translate">会員情報編集</p>
    </div>
  </div>
  <div class="row">
    <div class="col-1"></div>
    <!-- ユーザー詳細 -->
    <div class="col-10 users-container mt-5">
      <%= form_for @user do |f|%>
        <!-- エラーメッセージ文 -->
        <% if @user.errors.any? %>
          <%= @user.errors.count %>件のエラーが発生しました
            <% @user.errors.full_messages.each do |message| %>
              <%= message %>
            <% end %>
        <% end %>
        <!-- // -->

        <!-- 編集フォーム -->
        <div>
          <%= f.label :プロフィール画像, class: "col-xs-3" %>
        </div>
        <div>
          <%= attachment_image_tag @user, :profile_image, class: "raouded-circle", fallback: "noimage.png", size:"200x200" %>
        </div>
        <div class="new-field">
          <%= f.attachment_field :profile_image %>
        </div>
        <div class="new-field">
          <%= f.label :名前, class: "col-xs-3" %><br>
          <%= f.text_field :name, autofocus: true, autocomplete: "name", class: "col-xs-8", size:'50' %>
        </div>
        <div class="new-field">
          <%= f.label :メールアドレス, class: "col-xs-3" %><br>
          <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "col-xs-8", size:'50' %>
        </div>
        <div class="new-field">
          <%= f.submit "更新", class: "btn btn-success" %><p class="confirm-text">　　更新前に内容をご確認ください</p>
        </div>
        <!-- /編集フォーム -->
      <% end %>
    </div>
    <!-- /ユーザー詳細 -->
    <div class="col-1"></div>
  </div>
</div>

app/views/users/followers.html.erb
<div class="container animate__animated animate__swing">
  <div class="row">
    <div class="col-12">
      <h1 class="page-title">Followers</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <p class="page-title-translate">フォロワー一覧</p><br>
    </div>
  </div>
  <div class="row">
    <div class="col-1"></div>
    <div class="col-10 users-contents" style="padding: 0px;">
    <table class="table table-hover">
      <thead class="thead-color">
        <tr>
          <th>Image</th>
          <th>Name</th>
          <th>Following count</th>
          <th>Followers count</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
        <tr>
          <td class="align-middle">
            <%= link_to user_path(user) do %>
              <%= attachment_image_tag user, :profile_image, size:'50x50', class: "rounded-circle float-left", size:"50x50" ,fallback:"noimage.png" %>
            <% end %>
          </td>
          <td class="align-middle">
            <%= link_to user_path(user) do %>
              <%= user.name %>
            <% end %>
          </td>
          <td class="align-middle">フォロー数：<%= user.following.count %></td>
          <td class="align-middle">フォロワー数：<%= user.followers.count %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <!-- paginate users, class: "text-center" -->
    </div>
    <div class="col-1"></div>
  </div>
</div>

app/views/users/following.html.erb
<div class="container animate__animated animate__swing">
  <div class="row">
    <div class="col-12">
      <h1 class="page-title">Following</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <p class="page-title-translate">フォロー一覧</p><br>
    </div>
  </div>
  <div class="row">
    <div class="col-1"></div>
    <div class="col-10 users-contents" style="padding: 0px;">
    <table class="table table-hover">
      <thead class="thead-color">
        <tr>
          <th>Image</th>
          <th>Name</th>
          <th>Following count</th>
          <th>Followers count</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
        <tr>
          <td class="align-middle">
            <%= link_to user_path(user) do %>
              <%= attachment_image_tag user, :profile_image, size:'50x50', class: "rounded-circle float-left", size:"50x50" ,fallback:"noimage.png" %>
            <% end %>
          </td>
          <td class="align-middle">
            <%= link_to user_path(user) do %>
              <%= user.name %>
            <% end %>
          </td>
          <td class="align-middle">フォロー数：<%= user.following.count %></td>
          <td class="align-middle">フォロワー数：<%= user.followers.count %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <!-- paginate users, class: "text-center" -->
    </div>
    <div class="col-1"></div>
  </div>
</div>

app/views/users/index.html.erb
<%= render 'users/index', users: @users %>

app/views/users/show.html.erb
<div class="container animate__animated animate__swing">
  <div class="row">
    <div class="col-12">
      <% if current_user.id == @user.id %>
        <h1 class="page-title">My page</h1>
      <% else %>
        <h1 class="page-title">User page</h1>
      <%end%>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <p class="page-title-translate"><%= @user.name %>のマイページ</p>
    </div>
  </div>
  <div class="row">
    <div class="col-1"></div>
    <!-- ユーザー詳細 -->
    <div class="col-10 users-container mt-5">
      <div class="user-profile clearfix">
        <%= attachment_image_tag @user, :profile_image, class: "rounded-circle float-left", size: "100x100" ,fallback: "noimage.png" %>
        <h5>名前　：　<%= @user.name %></h5>
        <h5>メールアドレス　：　<%= @user.email %></h5>
        <%= render 'users/stats' %>
        <% if current_user == @user %>
          <%= link_to '会員情報編集', edit_user_path(@user.id), class: "btn btn-success float-right" %>
        <% end %>
        <!-- フォロー機能 -->
        <%= render 'relationships/follow_form' %>
      </div>
      <div class="user-postitem">
        <table class="table table-hover">
          <thead class="thead-color">
            <tr>
              <th class="text-center">Posts</th>
              <th class="text-center">Title</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @post_images.each do |post_image| %>
            <tr class="text-center">
              <td>
                <%= link_to post_image_path(post_image) do %>
                  <%= attachment_image_tag post_image, :image, size:"70x70", class: "shadow border border-secondary" %>
                <% end %>
              </td>
              <td class="align-middle"><%= post_image.title %></td>
              <% if post_image.user == current_user %>
              <td class="align-middle"><%= link_to 'Edit', edit_post_image_path(post_image) %></td>
              <td class="align-middle"><%= link_to 'Destory', post_image_path(post_image), method: :delete, "data-confirm" => "本当に削除しますか？" %></td>
              <% end %>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <!-- /ユーザー詳細 -->
    <div class="col-1"></div>
  </div>
</div>