config/routes.rb
Rails.application.routes.draw do

  # ログイン関係
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  # ユーザー関係
  root 'homes#top'
  get '/about' => 'homes#about'
  resources :post_images do
    resource :favorites, only:[:create, :destroy]
    resources :comments, only:[:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    member do
      get :following, :followers
    end
  end
  resources :articles, only: [:index, :show]

  resources :relationships, only: [:create,:destroy]
  # 管理者関係
  namespace :admin do
    root 'homes#top'
    resources :articles
    resources :users, only: [:index, :show, :edit, :update, :destroy]
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/homes/top.html.erb
<div class="container">
  <div class="row text-center">
    <div class="col">
      <div class="fadein">
        <p class="head">
          <%= link_to admin_articles_path do %>
            Articles <span class="head-translation">記事一覧</span>
          <% end %>
        </p>
        <p class="head">
          <%= link_to admin_users_path do %>
            Users <span class="head-translation">会員一覧</span>
          <% end %>
        </p>
        <p class="head">
          <%= link_to destroy_admin_session_path, method: :delete do %>
            Sign out <span class="head-translation">サインアウト</span>
          <% end %>
        </p>
      </div>
    </div>
  </div>
</div>