config/routes.rb
Rails.application.routes.draw do

  # ログイン関係
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  # ユーザー関係
  root 'homes#top'
  get '/about' => 'homes#about'
  resources :post_images do
    resource :favorites, only:[:create, :destroy]
    resources :comments, only:[:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    member do
      get :following, :followers
    end
  end
  resources :articles, only: [:index, :show]

  resources :relationships, only: [:create,:destroy]
  # 管理者関係
  namespace :admin do
    root 'homes#top'
    resources :articles
    resources :users, only: [:index, :show, :edit, :update, :destroy]
  end

end

app/models/post_image.rb
class PostImage < ApplicationRecord
  # アソシエーション
  belongs_to :user
  attachment :image
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true
  validates :content, presence: true
  validates :image, presence: true 
end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController
  before_action :authenticate_user!, only:[:new,:show]
  before_action :post_image_restrict, only:[:edit,:update,:destroy]

  def new
    @post_image = PostImage.new
  end

  def index
    @post_images = PostImage.includes(:user).page(params[:page]).per(10).order(created_at: :desc)
  end

  def create
    @post_image = PostImage.new(post_image_params)
    @post_image.user_id = current_user.id
    if @post_image.save
       redirect_to post_images_path, notice: "新規投稿されました"
    else
      render 'new'
    end
  end

  def show
    @post_image = PostImage.includes(comments: :user).find(params[:id])
    @comment = Comment.new
  end

  def edit
    @post_image = PostImage.find(params[:id])
  end

  def update
    @post_image = PostImage.find(params[:id])

    if @post_image.update(post_image_params)
      redirect_to post_image_path(@post_image), notice: "投稿内容を更新しました"
    else
      render 'edit'
    end
  end

  def destroy
    @post_image = PostImage.find(params[:id])
    @post_image.destroy
    redirect_back (fallback_location :root_path), notice: "投稿を削除しました"
  end

  private
    def post_image_params
      params.require(:post_image).permit(:user_id, :title, :content, :image)
    end

    def post_image_restrict
      post_image = PostImage.find(params[:id])
      if post_image.user != current_user
        redirect_to post_images_path, notice: "⚠️他人の投稿は編集できません"
      end
    end
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/views/post_images/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <h1 class="page-title animate__animated animate__jackInTheBox">Plants Edit</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <p class="page-title-translate animate__animated animate__jackInTheBox">投稿編集</p>
    </div>
  </div>
  <div class="row animate__animated animate__rotateInDownRight">
    <%= form_for @post_image do |f|%>
      <!-- エラーメッセージ文 -->
      <% if @post_image.errors.any? %>
        <%= @post_image.errors.count %>件のエラーが発生しました
        <% @post_image.errors.full_messages.each do |message| %>
          <%= message %>
        <% end %>
      <% end %>
      <!-- // -->

      <!-- 新規投稿フォーム -->
      <div class="plants-image">
        <%= attachment_image_tag @post_image, :image, class: "img-square", fallback: "no-image2.png", size:"200x200" %>
      </div>
      <div class="new-field">
        <%= f.attachment_field :image %>
      </div>
      <div class="new-field">
        <%= f.label :タイトル, class: "col-xs-3" %><br>
        <%= f.text_field :title, autofocus: true, autocomplete: "title", class: "col-xs-8", size:'40' %>
      </div>
      <div class="new-field">
        <%= f.label :投稿内容, class: "col-xs-3" %><br>
        <%= f.text_area :content, autofocus: true, autocomplete: "content", class: "col-xs-8", size:'65x10' %>
      </div>
      <div class="new-field">
        <%= f.submit "更新", class: "btn btn-success" %><p class="confirm-text">　　更新前に内容をご確認ください</p>
      </div>
    <% end %>
  </div>
</div>

app/views/post_images/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <h1 class="page-title collapse2 animate__animated animate__bounceInDown">Plants</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <p class="page-title-translate collapse3 animate__animated animate__backInRight">みんなの投稿</p>
    </div>
  </div>
  <div class="row animate__animated animate__fadeInUpBig">
    <% @post_images.each do |post_image| %>
      <div class="col-3 side-left"></div>
      <div class="col-8 post-container">
        <div class="plants-image text-center collapse4">
          <%= link_to post_image_path(post_image.id) do%>
            <%= attachment_image_tag post_image, :image, width: "100%", height: "100%", fallcack: "no-image2.png" %>
          <% end %>
        </div>
        <div class="block-content collapse5">
          <%= link_to user_path(post_image.user_id) do %>
            <%= attachment_image_tag post_image.user, :profile_image, class: "rounded-circle float-left", size:"70x70" ,fallback:"noimage.png" %>
          <% end %>
          <h4 id="post-title">
            <%= post_image.title %>
          </h4><br>
          <ul class="post-details">
            <li>By <%= post_image.user.name %>　</li>
            <li>
              <% if post_image.favorites.count == 0 %>
                <i class="far fa-heart"></i>
              <% else %>
                <i class="fas fa-heart" style="color: crimson;"></i>
              <% end %>
               <%= post_image.favorites.count %>
             </li>
            <li><i class="far fa-comment-dots"></i> <%= post_image.comments.count %>　</li>
            <li><i class="far fa-clock"></i> <%= post_image.created_at.strftime('%Y/%m/%d') %></li>
          </ul>
        </div>
      </div>
      <div class="col-3 side-right"></div>
    <% end %>
  </div>
  <%= paginate @post_images %>
</div>

app/views/post_images/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <h1 class="page-title animate__animated animate__jackInTheBox">Plants New</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <p class="page-title-translate animate__animated animate__jackInTheBox">写真投稿</p>
    </div>
  </div>
  <div class="row animate__animated animate__rotateInDownRight">
    <%= form_for @post_image do |f|%>
      <!-- エラーメッセージ文 -->
      <% if @post_image.errors.any? %>
            <%= @post_image.errors.count %>件のエラーが発生しました
            <% @post_image.errors.full_messages.each do |message| %>
                <%= message %>
            <% end %>
        <% end %>
      <!-- // -->

      <!-- 新規投稿フォーム -->
      <div class="plants-image">
        <%= attachment_image_tag @post_image, :image, class: "img-square", fallback: "no-image2.png", size:"200x200" %>
      </div>
      <div class="new-field">
        <%= f.attachment_field :image %>
      </div>
      <div class="new-field">
        <%= f.label :タイトル, class: "col-xs-3" %><br>
        <%= f.text_field :title, autofocus: true, autocomplete: "title", class: "col-xs-8", size:'40' %>
      </div>
      <div class="new-field">
        <%= f.label :投稿内容, class: "col-xs-3" %><br>
        <%= f.text_area :content, autofocus: true, autocomplete: "content", class: "col-xs-8", size:'65x10' %>
      </div>
      <div class="new-field">
        <%= f.submit "投稿", class: "btn btn-success" %><p class="confirm-text">　　投稿前に内容をご確認ください</p>
      </div>
    <% end %>
  </div>
</div>

app/views/post_images/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <h1 class="page-title animate__animated animate__jackInTheBox">Plants about</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <p class="page-title-translate animate__animated animate__jackInTheBox"><%= @post_image.user.name %>さんの投稿</p>
    </div>
  </div>
  <div class="row animate__animated animate__rotateInDownRight">
    <div class="col-1"></div>
    <!-- 投稿詳細内容 -->
    <div class="col-10 post_images_container mt-5">
      <div class="text-center">
        <%= attachment_image_tag @post_image, :image , width: "80%", height: "80%" %>
      </div>
      <div class="postimage-title">
        <h2><%= @post_image.title %></h2>
      </div>
      <div class="content">
        <span class="content-title">Content</span>
        <p><%= simple_format(@post_image.content) %></p>
      </div>
      <div class="post-users-content">
          <%= link_to user_path(@post_image.user) do %>
            <%= attachment_image_tag @post_image.user, :profile_image, class: "rounded-circle", size: "60x60" ,fallback: "noimage.png" %>
          <% end %>
          <ul class="post-details">
            <li>By <%= @post_image.user.name %>　</li>
            <!-- いいね機能 -->
            <li id="favorite_<%= @post_image.id %>">
                <%= render 'favorites/favorite', post_image: @post_image %>
            </li>
            <li>コメント <%= @post_image.comments.count %></li>
          </ul>
      </div>
      <!-- コメント一覧 -->
      <div id="comments_area">
        <%= render 'comments/index', post_image: @post_image %>
      </div>
      <!-- コメント入力 -->
      <% if user_signed_in? %>
        <%= render 'comments/form', comment: @comment, post_image: @post_image %>
      <% end %>
      <!-- 遷移リンクボタン -->
      <div class="link-btn">
        <div class="text-left link-left">
          <%= link_to '< Back', post_images_path %>
        </div>
        <% if current_user == @post_image.user %>
        <div class="text-right link-right">
          <%= link_to 'Edit >', edit_post_image_path(@post_image) %>
        </div>
        <% end %>
      </div>
    </div>
    <div class="col-1"></div>
  </div>
</div>